### ISSUE TITLE
TypeError: must be type, not classobj

### ISSUE THREAD

**Issue by shapecoder** [patvdleer/nefit-client-python#1]
installed nefit-client on a Raspberry Pi 3 running Python 2.7.9 using pip. Tried getting the status using the following in bash:

nefit-client --serial [myserial] --access-key [mykey] --password [mypass] --status

Got the following error:

Traceback (most recent call last):
  File "/usr/local/bin/nefit-client", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/nefit/cli.py", line 83, in main
    cli.run()
  File "/usr/local/lib/python2.7/dist-packages/nefit/cli.py", line 57, in run
    print(client.get_status())
  File "/usr/local/lib/python2.7/dist-packages/nefit/__init__.py", line 271, in get_status
    data = super(NefitClientCli, self).get_status()
TypeError: must be type, not classobj

**Comment by patvdleer** [comment]
I haven't extensively tested it on PY2.7, I'll check if I can reproduce this later today/tomorrow.

**Comment by patvdleer** [comment]
Bug is confirmed, seems to be https://stackoverflow.com/questions/1713038/super-fails-with-error-typeerror-argument-1-must-be-type-not-classobj#1713052

**Comment by patvdleer** [comment]
PyPi has been updated https://pypi.python.org/pypi/nefit-client/0.2.4 please reopen this doesn't fix it.
