### ISSUE TITLE
Nefit-client not working

### ISSUE THREAD

**Issue by chiel2603** [patvdleer/nefit-client-python#6]

**Comment by patvdleer** [comment]
@chiel2603 anything wrong?

**Comment by chiel2603** [comment]
@patvdleer I had an error linked to a password problem. I have tryed to remove this issue, sorry.

```
nefit-client --serial XXXXXXXXX --access-key XXXXXXXXXXXXXXXX, --password XXXXXXXXXX --status
Traceback (most recent call last): File "/srv/homeassistant/bin/nefit-client", line 11, in sys.exit(main()) File "/srv/homeassistant/lib/python3.5/site-packages/nefit/cli.py", line 92, in main cli.run() File "/srv/homeassistant/lib/python3.5/site-packages/nefit/cli.py", line 60, in run print(client.get_status()) File "/srv/homeassistant/lib/python3.5/site-packages/nefit/init.py", line 287, in get_status for k, v in data.items(): AttributeError: 'str' object has no attribute 'items'
```

**Comment by ndraganic** [comment]
I get the same error when I try to use the client: 
```
Traceback (most recent call last):
  File "/Users/ndraganic/Code/Python/superbosch/superbosch-env/bin/nefit-client", line 8, in <module>
    sys.exit(main())
  File "/Users/ndraganic/Code/Python/superbosch/superbosch-env/lib/python3.8/site-packages/nefit/cli.py", line 92, in main
    cli.run()
  File "/Users/ndraganic/Code/Python/superbosch/superbosch-env/lib/python3.8/site-packages/nefit/cli.py", line 60, in run
    print(client.get_status())
  File "/Users/ndraganic/Code/Python/superbosch/superbosch-env/lib/python3.8/site-packages/nefit/__init__.py", line 287, in get_status
    for k, v in data.items():
AttributeError: 'str' object has no attribute 'items'
```

Like above, I wanted to se the status.

**Comment by patvdleer** [comment]
mentalNote: add proper error handling

**Comment by patvdleer** [comment]
@ndraganic I just did a quick update, could you check if it now does throw an error? I know it still doesn't tell you exactly that the username/password is incorrect.

**Comment by ndraganic** [comment]
Now it's a different one:
`nefit.NefitResponseException: Unable to get /ecus/rrc/uiStatus`
and it doesn't exit, it waits for the interrupt.

**Comment by patvdleer** [comment]
that's currently "a feature", I still need to split up auth failures and regular connection errors

**Comment by ndraganic** [comment]
so are you saying my credentials don't work? it connects just fine when I log in to the Bosch Control App

**Comment by patvdleer** [comment]
I get that error when my credentials are wrong yes, I haven't found a way to easily test/check this and I'm moving tomorrow so I'm limited in time.

**Comment by ndraganic** [comment]
ok, it's not urgent. one more thing, your instructions say to start client as `Nefit client` but I get "Nefit: command not found". i use `nefit-client`instead. is this something irregular?
